### ISSUE TITLE
ChangeOutput Placeholders issue

### ISSUE THREAD

**Issue by M4h45amu7x** [Kqliber/Expansion-ChangeOutput#2]
ChangeOutput Placeholders show empty if the condition contains %player_name% and player name beginning or ending with _

Placeholder:
`%changeoutput_equals_{player_name}_{player_name}_&cnope_&a{player_displayname}%`

**Comment by PetyXbron** [comment]
I have the same problem. This needs to be solved.

## **If a player name contains underscore (_), ChangeOutput evaluates it as the start or end of an argument.**

**Look at this image, please:**
![Screenshot_631](https://user-images.githubusercontent.com/35902119/161442353-d8bd0fcf-8d62-486b-bbe6-10632ad63bad.png)

- **Red:** proof of player name ending
- **Pink:** proof of player statistic value matching
- **Brown:** underscore in the player name
- **Green:** part of player name and characters before it gets deleted

**Comment by PetyXbron** [comment]
@Kqliber @BlitzOffline

**Comment by LordYarkan** [comment]
I see that months have passed with this error and they haven't fixed it then :c

**Comment by Weasel-Beans** [comment]
I've also run into this issue. It's a shame because it can only function for users that don't use underscores in their names when trying to run commands.

_However_ I may have found a workaround that solves this problem, at least for my issue. **Instead of checking for the player's username, check for their UUID**, as that does not contain underscores.

For example, use {player_UUID} instead of {player_name}.

But in areas where this doesn't help, I'd also like to see this fixed somehow.

**Comment by Kqliber** [comment]
ok fine i fixed it
The change i've made requires a new format in the placeholder
`%changeoutput_<options>_input:<your input>_matcher:<to check against>_ifmatch:<output if true>_else:<output if false>%`
example:
`%changeoutput_contains_input:some_username_matcher:some_ifmatch:Contains!_else:Doesnt Contains%`

I have only tested minimally, so if people could test this too that will be great!
https://cdn.discordapp.com/attachments/726924932239327232/990714996172402718/Expansion-ChangeOutput.jar

**Comment by Weasel-Beans** [comment]
Seems to work good! Haven't noticed any issues.

**Comment by PetyXbron** [comment]
OMG 😯! It works, thank you. It's a little bit complicated, but updating my 10 holograms with it took me like 6 minutes, so it's worth it. Didn't find any bugs yet.

**Comment by Kqliber** [comment]
Great! I will be closing this issue now as it seems to work. This build of the expansion has also been uploaded to the ecloud (https://api.extendedclip.com/expansions/changeoutput/), or you may grab it from in-game using `/papi ecloud download changeoutput`
