### ISSUE TITLE
Expansion does not parse color codes after PAPI update.

### ISSUE THREAD

**Issue by Weasel-Beans** [Kqliber/Expansion-ChangeOutput#3]
PlaceholderAPI update 2.11.2 removed the automatic color code parsing from the plugin. The expansion would need to be updated to re-add this important feature. Thanks

https://www.spigotmc.org/resources/placeholderapi.6245/update?update=462869

**Comment by Kqliber** [comment]
I feel like this should be up to the plugin where the placeholder is being parsed to handle colours, unless there's a specific reason why colours must be parsed within the expansion.

**Comment by Andre601** [comment]
PlaceholderAPI no longer parses colours, as it was considered out of scope (A placeholder parser shouldn't really deal with colour code handling) and also caused issues with HEX colours.

So it's recommended to just parse it within the expansion itself if desired. It's literally a one-line code that needs to be used here.
