### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tanerx** [Kqliber/Expansion-ChangeOutput#6]
Hello.
Can we get range options please?

**Comment by Kqliber** [comment]
You can use ranges by nesting another changeoutput placeholder within the ifmatch/else
If you need deeper nesting of placeholders, you can combine the [utils expansion](https://api.extendedclip.com/expansions/utils/) too, such as:

`%utils_parse_changeoutput_>=_input:{PLACEHOLDER}_matcher:MIN-VALUE_ifmatch:{changeoutput_<=_input:{PLACEHOLDER}_matcher:MAX-VALUE_ifmatch:yes_else:no}_else:no%`
